# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alberto Brezmes
title: Head of Security Processes & Advanced Architectures
# email: name@example.com
website: https://brezmes.github.io/ 

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: brezmes
github_username:  brezmes
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: brezmes
linkedin_username: alberto-brezmes
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: brezmes
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Hi, my name's Alberto I'm passionate about technology, and in particular everything related to the cloud world and security. I have experience in the design of highly scalable systems (<mark>Cloud Architect</mark>), security in software development (<mark>DevSecOps</mark>), and <mark>Big Data</mark> analysis systems, and systems based on artificial intelligence (<mark>AI</mark>). 
 
 I have worked from small startups to large banks and for numerous IBEX35 companies. 
 
 On the management perspective, I'm able to design and execute business and strategic plans, recruit and retain talent, and build ownership and brand.

 I am most skilled in: <mark>AWS</mark>,  <mark>Music</mark>  and  <mark>Sports</mark>

 > _There is nothing impossible if you love what you do and I love it_

content:
  - title: Latest Confs & Others # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      **Confs:**
      - [Pannel Session Horizon Cloud Summit 2020](https://twitter.com/HCLOUD_Project/status/1331200905832697856?s=20){:target="_blank"}
      - [Participation in table on Hybrid Cloud Security, for GlobbTV](http://live.globbtv.com/vod-sesion-especial-hybrid-cloud-security-20-de-septiembre-de-2018){:target="_blank"}
      - [Participation in table on 'The Evolution of DDoS Threats and the Zero Trust Model' for ComputerWorld / Cloudflare](https://www.computerworld.es/pubs/cw1360/index.html?page=137){:target="_blank"}
      - [Participation in the CybersecForum](https://www.youtube.com/watch?v=wkuHmQefpsQ&t=25s){:target="_blank"}
      - [AWS Madrid Summit. Security in your business.](https://www.youtube.com/watch?v=egchpZt5ywE){:target="_blank"}

      **Certifications & Courses:**
      - PowerMBA (January 2021)
      - AWS Security Engineering (July 2020)
      - AWS Advanced Architecting (June 2020)
      - AWS Certified Solutions Architect - Associate (June 2018) 
      - Systems Operations on AWS (February 2015)
      - M102: MongoDB for DBAs (April 2014)
      - M101P: MongoDB for Developers (March 2014)
      - AWS Essentials (July 2013)


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Inetum
        link: inetum.com
        sub_title: Head of Security Processes and Advanced Architectures
        caption: February 2020 - Present
        quote: >
          I came to Inetum, formerly Gfi, with the objective of being one of the 3 founders of a new security company, focused on strategic and technological consulting, and the development of cybersecurity products, in my case, within the field of cloud security.
        description: | # this will include new lines to allow paragraphs
            We have created the Digital Risk area, we have developed collaborations with different companies and executed amazing projects related to the field of Secure Development (DevSecOps), Security and Cloud Solutions.
            In my specific case, I am in charge of creating and leading a Technology Consultancy team, designing the bases of what will be a Cloud Security product, both at a functional and business level, and in addition to all this, I am in charge of monitoring the area at the Operations, People Management and Economic and Financial Control levels.
            On the other hand, I am the connection with the Cloud providers within the area, in this case mainly with AWS and I manage the relationship with the Partner.
            
            Among the products we have developed are the following:
            - Platform for sharing sensitive information securely and easily. In production at client.
            - Platform for detection and protection of user browsing. In the deployment phase.
            - Security data analysis platform for incident prediction. In the deployment phase.

            The main technologies that we work with our customers are:
            AWS, Kubernetes, Python, Cloud Security, DevSecOps, Big Data, Machine Learning.

      - layout: left
        title: Universitat de Lleida, NextIBS
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        caption: September 2019 - December 2019
        description: | # this will include new lines to allow paragraphs
            Cloud Security Masterclass at “Máster in Cybersecurity”

      - layout: left
        title: Universidad Europea de Madrid, UEM
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Co-author
        caption: February 2018 - July 2019
        description: | # this will include new lines to allow paragraphs
            Co-author for Cloud Security at “Máster Universitario de Cloud Computing Online”

      - layout: left
        title: BBVA Next Technologies
        link: www.bbvanexttechnologies.com
        link_text: bbvanexttechnologies.com
        sub_title: Business Manager | Head of Global DevOps | Labs Adviser
        caption: September 2016 - February 2020
        description: | # this will include new lines to allow paragraphs
            **Business Manager. Security Specialist.** Account Manager for security services accounts, multi-cloud projects, and the SaaS platform on which the services are offered. Management of a four people team to offer hacking services, risk analysis, cloud and development tools.
            
            Technologies: AWS, GCP, Azure, EKS


            **Head of Global DevOps**. BBVA Security Architecture. Design a common platform for all products on Security Architecture area, to design a common model for deployments and the
            integration tools to help product teams do devops philosophy. “Ops as Product”. Management of a team with eight people in Spain and support of two in Mexico. Governance of AWS accounts where all environments are running.
            Labs Adviser, I4S squad Innovation Board member. Connector of production requirements and innovation, to define new solutions for cloud environments security problems.
            
            Technologies: AWS, Openstack, Terraform, Ansible, Scrum-Kanban, Kubernetes, Graylog, Kafka.

      - layout: left
        title: Ventura24, Zeal Group
        sub_title: Enterprise Cloud Strategy Member | Platform Transformation Technical Lead
        caption: September 2015 - September 2016
        description: | # this will include new lines to allow paragraphs
            **Enterprise Cloud Strategy Member**. Design of new cloud with Rackspace Openstack Solution as provider, where all products (Zeal Group) will be running, main requirement is a scalable architecture with “jackpot as a service” focus.
            
            Technologies: Rackspace, Openstack, Ansible, Docker, Mesos, Marathon, DC/OS


            **Platform Transformation Technical Lead**. Common pipeline of CI / CD design and deploy for all products of the company, container orchestration and microservices based..

            Technologies: Jenkins, Spring Boot, Ansible, Docker


      - layout: left
        title: i4s, BBVA
        sub_title: Lead DevSecOps | Cloud Solutions Architect | Systems Integrator and ScrumMaster | Head of Technical Systems
        caption: February 2014 - September 2015
        description: | # this will include new lines to allow paragraphs
            **Lead SecDevOps, Cloud Solutions Architect**, I4S. Responsible of the management and administration of enterprise cloud with 8 Virtual Private Clouds, and around 100 virtual machines. Automation in the administration and securitization. Design and deployment of VPCs, and related projects. Deploy and management a Forge for software development.
            
            Technologies: AWS, puppet, chef, ansible, terraform.


            **System integrator and ScrumMaster**, Digital Bank, BBVA. Design and development a tool for automatic security analysis of infrastructure and code.

            Technologies: AWS, Fortify, SonarQube, Jenkins, GitLab, Atlassian, Taiga, Puppet, Python, Bash.


            **Head of Technical Systems**, Logical Security, IT Risk, Fraud & Security, BBVA. Technical Systems team management, administration, automation and optimization of physical and virtual infrastructure of the department with approximately 350 virtual machines and 75 physical. Support to developers.

            Technologies: HP Blade, HP Enclosure, HP Virtual Connect, NetApp, VMware Suite, Nagios, GitLab, Atlassian, Taiga, Puppet, Python, Bash, Scrum, Kanban

      - layout: left
        title: Creania Labs SL
        sub_title: DevOps
        caption: February 2013 - January 2014
        description: | # this will include new lines to allow paragraphs
            **DevOps**. Researching on mobile technologies and cloud. Design and implementation of systems for live streaming and transcoding by HLS and HDS protocols. Design and implementation of scalable architectures in cloud. Customer contact and service providers such as Amazon Web Services. Design, implementation and management of a Forge with support for software development with GIT, Redmine, Jenkins, Chef.
            Production projects: 
            - [MegaStarFM](www.megastar.fm){:target="_blank"}
            - [Tecnopasion](www.tecnopasion.com){:target="_blank"}

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad Politécnica de Madrid (UPM)
        caption: 2009 - 2015
        sub_title: Computers Engineer Degree
        quote: >
          I studied it, but I didn't finish it
        description: | # this will include new lines to allow paragraphs
          During my time at "Escuela Técnica Superior de Ingeniería de Sistemas Informáticos" I learned a lot about how to structure the problems to be solved, and some basic knowledge about the technology, but it was not until I started working that I was able to develop my skills.

          I spent a lot of my free time as a Students Representation member of the *Universidad Politécnica de Madrid* taking on roles such as *School Students President* and *Secretary*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in cloud computing and security, some of my other interests and hobbies are:
      - Family & Friends
      - Running
      - Cooking
      - Mountain Sports
      - Gaming

      Look at this cool image  
      ![Trees](images/landscape.jpeg "Roque Nublo")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
